name: pharma_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  #run: "flutter run -t lib/main_development.dart --flavor development"
  # you can define more commands like this: "rps gen"
  #gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
  splash: "flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml"
  gen: "flutter pub run build_runner build --delete-conflicting-outputs"
  intl: "flutter pub run intl_utils:generate"
  icons: "flutter pub run flutter_launcher_icons:main"

  freezed: "flutter pub add freezed_annotation|flutter pub add --dev build_runner|flutter pub add --dev freezed"
  json: "flutter pub add json_annotation|flutter pub add --dev json_serializable"
  # and even nest them!
#  build:
#    android:
#      # rps build android apk
#      apk: "flutter build --release apk --flavor production"
#      # rps build android appbundle
#      appbundle: "flutter build --release appbundle --flavor production"
#      # and so on...

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  intl: 0.17.0
  file_picker: ^5.0.0
  intl_utils: ^2.7.0
  flutter_riverpod: ^2.1.1
  provider: ^6.0.5
  riverpod_generator: ^1.0.6
  firebase_core: ^2.13.0
  flutter_native_splash: ^2.2.19
  #flutter_native_splash: ^2.2.11
  freezed_annotation: ^2.2.0
  global_configuration: ^2.0.0-nullsafety.1
  shared_preferences: ^2.1.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  dio: ^4.0.6
  retry: ^3.1.0
  uuid: ^3.0.7
  flutter_credit_card: ^3.0.4
  vector_math: ^2.1.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.8
  flutter_html: ^3.0.0-beta.2
  footer: ^0.0.4
  csc_picker: ^0.2.7
  permission_handler: ^10.4.3

  firebase_auth: ^4.9.0
  firebase_messaging: ^14.6.4
  awesome_notifications: ^0.7.4
  firebase_dynamic_links: ^5.0.4
  firebase_analytics: ^10.2.0
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1
  package_info: ^2.0.2
  timeago: ^3.3.0
  talker: ^3.1.1
  flutter_facebook_auth: ^5.0.11

  location: ^4.4.0
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  geocoder2: ^1.4.0
  geocoding: ^2.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  map_location_picker: ^1.1.0

  flutter_typeahead: ^4.3.1

  random_string: ^2.3.1

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0

  flutter_otp_text_field: ^1.1.1
  flutter_advanced_drawer: ^1.3.5

  awesome_dialog: ^3.1.0
  sizer: ^2.0.15
  webview_flutter: ^2.0.9

  # Chat
  detectable_text_field: ^2.0.4
  emoji_picker_flutter: ^1.5.4
  cross_file: ^0.3.3+4
  image_picker: ^0.8.7+4
  fluttertoast: ^8.2.1
  photo_view: ^0.14.0
  flutter_stripe: ^9.4.0
  cached_network_image: ^3.2.3
#
#dependency_overrides:
#  map_location_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.4
 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/cfg/
    - assets/ico/
    - assets/immagini/
    - assets/app_icon/
    - assets/immagini_pharma/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/immagini_pharma/logo_small.png"
